# fly.toml app configuration file generated for broken-dawn-2911 on 2023-08-16T18:14:30-04:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "broken-dawn-2911"
primary_region = "iad"

[deploy]
  release_command = "npm run build"

[env]
  PORT = "8080"

[processes]
  app = "node app.js"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[[http.service_checks]]
  grace_period = "10s"
  interval = "30s"
  method = "get"
  timeout = "5s"
  path = "/"